#!/bin/bash

# Deploy schema.sql to Neon database
# This script provides instructions and safety checks

echo "🚀 Schema Deployment Script"
echo "=========================="
echo ""
echo "⚠️  WARNING: This will create/drop tables in your Neon database!"
echo ""
echo "📋 Pre-deployment Checklist:"
echo ""
echo "1. ✅ Database roles created (app_user, readonly_user)"
echo "   Run: scripts/setup-neon-roles.sql in Neon SQL Editor"
echo ""
echo "2. ✅ Backup existing data (if any)"
echo "   Export important data before running schema.sql"
echo ""
echo "3. ✅ Verify connection string"
echo "   Check .env.local has correct LCT_DATABASE_URL"
echo ""
echo "📝 Preferred Workflow:"
echo ""
echo "1. Apply migrations via npm (safe, incremental):"
echo "   npm run db:migrate"
echo ""
echo "2. Check status (optional):"
echo "   npm run db:migrate:status"
echo ""
echo "3. Verify permissions:"
echo "   Run: scripts/test-neon-config.sql"
echo ""
echo "⚙️  Manual Fallback (only if migrations are not available):"
echo "1. Open Neon Dashboard → SQL Editor"
echo "2. Copy and paste the contents of: scripts/schema.sql"
echo "3. Review the script carefully (it recreates tables)"
echo "4. Execute the script"
echo "5. Verify tables were created:"
echo "   SELECT table_name FROM information_schema.tables"
echo "   WHERE table_schema = 'public' ORDER BY table_name;"
echo ""
echo "⚠️  Important Notes:"
echo "   - email_list table is NOT dropped (preserves newsletter signups)"
echo "   - All other tables will be dropped and recreated"
echo "   - This manual path is destructive - prefer migrations!"
echo ""
echo "✅ After deployment, test with:"
echo "   ./scripts/test-neon-connection.sh"
echo ""

